### PR TITLE
Added new test webgl/canvas discovery graph

### PR DESCRIPTION
**Pull request by Canain**

### CODE REVIEW

**Comment by pviolette3** [comment]
Hi, This is cool. Please commit your source files, and build files you used to create this. 

Thanks.

**Comment by pviolette3** [comment]
Found the source here https://github.com/Canain/Discovery. Is this correct?

Good next step would be to add click events, for comparison. Good work :+1:

**Comment by Canain** [comment]
Yes, that is the correct source repo. Should I put the compiler files inside this repository?

**Comment by pviolette3** [comment]
Please do.

**Comment by pviolette3** [comment]
So, please commit both. Source files must be included. We can auto generate the compiled files, so we do not necessarily need these in the repo. For simplicity, we can keep them in.

**Pull request merged**
